export let DB = [

    {
       nombre : 'La Chica Salvaje',
       tituloIngles: 'Where the Crawdads Sing',
       estreno: '01-Sept-2022',
       genero:'Drama',
       duracion:'125 Min',
       recomendacion: 'Recomendada para Mayores de 12 años',
       fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula1.png?alt=media&token=167b81fd-fd8c-4b00-9399-2bef88632d87',

   },
   
  {
       nombre : 'El Arbol Rojo',
       tituloIngles:'',
       estreno: '01-Sept-2022',
       genero:'Aventura, Drama',
       duracion:'94 Min',
       recomendacion: 'Recomendada para Mayores de 12 años',
       fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula2.png?alt=media&token=90f778cd-89bc-487e-8ffe-a872564a5571',
     
   },
   
   {
       nombre : 'Dragon Ball Super: Super Hero',
       tituloIngles:'Dragon Ball Super: Super Hero',
       estreno: ' 18-Ago-2022',
       genero:'Animación',
       duracion:'100 Min',
       recomendacion: 'Recomendada para Mayores de 12 años',
       fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula3.jpg?alt=media&token=fe50f728-c915-46e7-ba4a-439705ddae4a',
   },
   
   {
        nombre : 'Lo Que Arde',
        tituloIngles:'Fire Will Come',
        estreno: '01-Sept-2022',
        genero:'Drama',
        duracion:'86 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula4.png?alt=media&token=7fa818a0-15dc-4491-ae0a-05d2cbde6e05',
    },

    {
        nombre : 'Vértigo',
        tituloIngles:'Fall',
        estreno: '25-Ago-2022',
        genero:'Suspenso',
        duracion:'107 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula5.png?alt=media&token=e02014ed-025a-44c2-a7b9-4b8ca5a2a4ee',
    },

    {
        nombre : 'Caceria de Brujas',
        tituloIngles:'Witch Hunt',
        estreno: '01-Sept-2022',
        genero:'Terror, Thriller',
        duracion:'92 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula6.png?alt=media&token=e7afe95e-2a26-4e6d-9b39-9db223414c4c',
    },

    {
        nombre : 'Tren Bala',
        tituloIngles:'Bullet Train',
        estreno: '04-Ago-2022',
        genero:'Acción, Thriller',
        duracion:'126 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula7.jpg?alt=media&token=35e471b3-aa1c-44ce-ae88-4685fafab6f8',
    },

    {
        nombre : '30 Noches Con Mi Ex',
        tituloIngles:'',
        estreno: '01-Sept-2022',
        genero:'Comedia',
        duracion:'95 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : 'https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula8.png?alt=media&token=51b56e11-4701-4f43-bc42-4cee899705d8',
    },
   

]