export let DB = [

    {
       nombre : 'La Chica Salvaje',
       tituloIngles: 'Where the Crawdads Sing',
       estreno: '01-Sept-2022',
       genero:'Drama',
       duracion:'125 Min',
       recomendacion: 'Recomendada para Mayores de 12 años',
       fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula1.png?alt=media&token=167b81fd-fd8c-4b00-9399-2bef88632d87','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2Fchica%20banner.jpg?alt=media&token=acde666d-458d-44e9-b4b1-fcd59c65ebe9'],
       trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FLa%20Chica%20Salvaje%20-%20Tr%C3%A1iler%20Oficial.mp4?alt=media&token=57d66038-6dad-4246-9819-6fe92b0b65ca'
    
   },
   
  {
       nombre : 'El Arbol Rojo',
       tituloIngles:'',
       estreno: '01-Sept-2022',
       genero:'Aventura, Drama',
       duracion:'94 Min',
       recomendacion: 'Recomendada para Mayores de 12 años',
       fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula2.png?alt=media&token=90f778cd-89bc-487e-8ffe-a872564a5571','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2Farbol%20banner.jpg?alt=media&token=4b7868e8-d552-4698-b22e-9736f34998a5'],
       trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FEl%20%C3%81rbol%20Rojo%20_%20Tr%C3%A1iler%20Oficial.mp4?alt=media&token=89104175-c4ba-4795-861f-cf5f9369a448'
     
   },
   
   {
       nombre : 'Dragon Ball Super: Super Hero',
       tituloIngles:'Dragon Ball Super: la Super Hero',
       estreno: ' 18-Ago-2022',
       genero:'Animación',
       duracion:'100 Min',
       recomendacion: 'Recomendada para Mayores de 12 años',
       fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula3.jpg?alt=media&token=fe50f728-c915-46e7-ba4a-439705ddae4a','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2FbanerEnsayo.jpg?alt=media&token=b10383bf-c30f-48f1-a439-bd230235462e'],
       trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FDragon%20Ball%20Super_%20SUPER%20HERO%20-%20Tr%C3%A1iler%20Final%20(Doblado).mp4?alt=media&token=8fef9a91-e719-478e-bd35-68ebe49948a3'
   },
   
   {
        nombre : 'Lo Que Arde',
        tituloIngles:'Fire Will Come',
        estreno: '01-Sept-2022',
        genero:'Drama',
        duracion:'86 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula4.png?alt=media&token=7fa818a0-15dc-4491-ae0a-05d2cbde6e05','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2Flo_que_arde_gente%20banner.jpg?alt=media&token=104605b7-e7e9-4fb5-85af-621b1edabac9'],
        trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FLo%20que%20arde%20-%20Tr%C3%A1iler%20_%20Filmin.mp4?alt=media&token=53d11c78-75c9-40c2-b4cb-146ed462b9a2'
    },

    {
        nombre : 'Vértigo',
        tituloIngles:'Fall',
        estreno: '25-Ago-2022',
        genero:'Suspenso',
        duracion:'107 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula5.png?alt=media&token=e02014ed-025a-44c2-a7b9-4b8ca5a2a4ee','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2Fvertigo%20banner.jpg?alt=media&token=09d446c9-93bb-4b78-be6b-455981e8357b'],
        trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FV%C3%A9rtigo%20(Fall)%20-%20Trailer%20Oficial%20Doblado%20al%20Espa%C3%B1ol.mp4?alt=media&token=809833df-f63c-4e77-ab7c-2a4150f57ed2'
    },

    {
        nombre : 'Caceria de Brujas',
        tituloIngles:'Witch Hunt',
        estreno: '01-Sept-2022',
        genero:'Terror, Thriller',
        duracion:'92 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula6.png?alt=media&token=e7afe95e-2a26-4e6d-9b39-9db223414c4c','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2Fcaceria-de-brujas%20banner.jpg?alt=media&token=e4e11b53-c692-4592-96d4-07853f6c0b5e'],
        trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FCacer%C3%ADa%20de%20Brujas%20-%20Trailer%20Oficial.mp4?alt=media&token=03596d4b-00ab-4924-81e8-d97e5ae88545'
    },

    {
        nombre : 'Tren Bala',
        tituloIngles:'Bullet Train',
        estreno: '04-Ago-2022',
        genero:'Acción, Thriller',
        duracion:'126 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula7.jpg?alt=media&token=35e471b3-aa1c-44ce-ae88-4685fafab6f8','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2Ftren%20bala%20banner.jpg?alt=media&token=83f76ce3-77c3-4dad-bcb4-20fbc4046d9c'],
        trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2FLo%20que%20arde%20-%20Tr%C3%A1iler%20_%20Filmin.mp4?alt=media&token=53d11c78-75c9-40c2-b4cb-146ed462b9a2'
    },

    {
        nombre : '30 Noches Con Mi Ex',
        tituloIngles:'',
        estreno: '01-Sept-2022',
        genero:'Comedia',
        duracion:'95 Min',
        recomendacion: 'Recomendada para Mayores de 12 años',
        fotos : ['https://firebasestorage.googleapis.com/v0/b/cine-2ddbf.appspot.com/o/pelicula8.png?alt=media&token=51b56e11-4701-4f43-bc42-4cee899705d8','https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/bannerCine%2F30%20noches%20banner.jpg?alt=media&token=ea6596d0-3ea2-48f9-9156-f7149162a9e0'],
        trailer:'https://firebasestorage.googleapis.com/v0/b/livtiendatcc.appspot.com/o/trailersCine%2F30%20noches%20con%20mi%20ex%20_%20Tr%C3%A1iler%20Oficial.mp4?alt=media&token=a5b88006-7447-4ae6-ad4a-fd35ac6ce918'
    },
   

]